-- [ XII ] TRANSACTION 명령어 : COMMIT (트랜잭션 반영) ; 
-- ROLLBACK (트랜잭션 취소);
-- SAVEPOINT (트랜잭션 분할);
-- 트랜잭션에는 DML 명령만 쌓임 ( INSERT,DELETE )
DROP TABLE DEPT01;
CREATE TABLE DEPT01 AS SELECT * FROM DEPT;
SELECT * FROM DEPT01;
DELETE FROM DEPT01;
SELECT * FROM DEPT01;
-- 트랜잭션에는 DELETE 하나만 쌓여있음
ROLLBACK;        -- ROLLBACK 해서 DELETE 취소됨      
-- ROLLBACK 해서 새로운 트랜잭션 시작
DELETE FROM DEPT01 WHERE DEPTNO=40;
COMMIT;
SELECT * FROM DEPT01; -- 데이터베이스 그대로를 출력 - 10,20,30

DELETE FROM DEPT01 WHERE DEPTNO=30;
SELECT * FROM DEPT01; -- 10,20
SAVEPOINT C1; -- C1지점 : 10,20번 부서 

DELETE FROM DEPT01 WHERE DEPTNO=20;
SELECT * FROM DEPT01;  -- 10
SAVEPOINT C2;  -- C2지점 - 10번부서

DELETE FROM DEPT01 WHERE DEPTNO=10;
SELECT * FROM DEPT01;

ROLLBACK  TO C2;
SELECT * FROM DEPT01;  -- 10번 부서만 남아있음
ROLLBACK TO C1;
SELECT * FROM DEPT01;  -- 10,20번 부서 남아있음
COMMIT;
SELECT * FROM DEPT01;




