--  [ XI ] 인덱스 : 조회를 빠르게 하는 인덱스
SELECT * FROM USER_INDEXES;  -- 딕셔너리뷰에서 SCOTT이 소유한 인덱스 정보
-- PRIMARY KEY 는 이미 인덱스가 같이 만들어짐
-- 빠른 검색을 위해서 인덱스를 사용한다.
-- SELECT 문의 처리속도를 향상시키기 위해 사용
--  추가,수정,삭제가 많이 일어나는것들은 오히려 인덱스를 사용하면 속도가 느려진다.
DROP TABLE EMP01;
CREATE TABLE EMP01 AS SELECT * FROM EMP; -- EMP내용과 같은 EMP01 생성
SELECT * FROM EMP01; -- 14행
INSERT INTO EMP01 SELECT * FROM EMP01; -- 1번 반복 28행 2번 56행 
SELECT TO_CHAR(COUNT(*),'9,999,999') FROM EMP01;
INSERT INTO EMP01 SELECT * FROM EMP01; -- 11번 반복 (11만4천개) 
INSERT INTO EMP01 (EMPNO, ENAME, DEPTNO) VALUES (1111,'HONG',40);
INSERT INTO EMP01 SELECT * FROM EMP01; -- 3번 HONG 넣기위해 (91만개)
SELECT TO_CHAR(COUNT(*),'9,999,999') FROM EMP01;  

SELECT * FROM EMP01 WHERE ENAME='HONG'; --  인덱스 생성 전 : 0.017초
CREATE INDEX IDX_EMP_ENAME ON EMP01(ENAME); -- 인덱스 생성 -- 0.368초
--CREATE INDEX 인덱스 이름 ON 어떤테이블의(어떤필드);

SELECT * FROM EMP01 WHERE ENAME='HONG'; -- 인덱스 생성 후 : 0.001초 
SELECT * FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_EMP01_ENAME';
COMMIT;
INSERT INTO EMP01 SELECT * FROM EMP01;  -- 인덱스 생성 후 INSERT 할 시   21.451초
ROLLBACK;   --  180만개에서 90만개로 가는 과정  취소과정 ( 10.3초)
DROP INDEX IDX_EMP_ENAME;
INSERT INTO EMP01 SELECT * FROM EMP01;  -- 인덱스 제거후 INSERT 시간 0.903초
SELECT TO_CHAR(COUNT(*),'9,999,999') FROM EMP01; 






