DROP TABLE CUS_LEVEL;
DROP TABLE CUSTOMER;

CREATE TABLE CUS_LEVEL(    -- CUS_LEVEL 테이블 생성
    LEVELNO NUMBER(2) PRIMARY KEY,
    LEVELNAME VARCHAR2(30) NOT NULL );

CREATE TABLE CUSTOMER(   -- CUSTOMER 테이블 생성
    CNO NUMBER(2) PRIMARY KEY,
    CNAME VARCHAR2(30) NOT NULL,
    JOINDATE DATE DEFAULT SYSDATE,
    PHONE VARCHAR2(30) UNIQUE,
    POINT NUMBER(5),
    LEVELNO REFERENCES CUS_LEVEL(LEVELNO) );

DROP SEQUENCE CUS_SQ;
CREATE SEQUENCE CUS_SQ   -- CNO에 넣을 CUS_SQ 시퀀스 생성
    MAXVALUE 99
    NOCACHE
    NOCYCLE;

-- CUS_LEVEL INSERT
INSERT INTO CUS_LEVEL VALUES (1,'VVIP');
INSERT INTO CUS_LEVEL VALUES (2,'VIP');
INSERT INTO CUS_LEVEL VALUES (3,'NORMAL');
INSERT INTO CUS_LEVEL VALUES (4,'BLACK');
-- CUSTOMER INSERT
INSERT INTO CUSTOMER VALUES (CUS_SQ.NEXTVAL , '홍길동',  '22/03/10' , '010-9999-9999' , 0 , 1);
INSERT INTO CUSTOMER VALUES (CUS_SQ.NEXTVAL , '이철수',  '22/04/19' , '010-8888-8888' , NULL , 2);

SELECT * FROM CUSTOMER;
SELECT * FROM CUS_LEVEL;

-- 출력
SELECT CNO, CNAME, TO_CHAR(JOINDATE,'YYYY-MM-DD') "JOINDATE" , PHONE, POINT, LEVELNAME
    FROM CUSTOMER C, CUS_LEVEL L
        WHERE C.LEVELNO = L.LEVELNO;

COMMIT;









