-- 강아지 분양 게시판 테이블
DROP SEQUENCE DBOARD_SEQ;

CREATE SEQUENCE DBOARD_SEQ
    MAXVALUE 999999
    NOCACHE
    NOCYCLE;
    
DROP TABLE DOG_BOARD;

CREATE TABLE DOG_BOARD(
    D_NUM NUMBER(6) PRIMARY KEY,
    AID REFERENCES ADMIN(AID) NOT NULL,
    DID REFERENCES DOG(DID) NOT NULL,
    D_TITLE VARCHAR2(30) NOT NULL,
    D_CONTENT VARCHAR2(3000) NOT NULL,
    D_RDATE DATE DEFAULT SYSDATE NOT NULL,
    D_HIT NUMBER(6) DEFAULT 0 NOT NULL,
    D_IP VARCHAR2(50) NOT NULL,
    D_IMAGE1 VARCHAR2(30) NOT NULL,   -- 최소 한장 첨부
    D_IMAGE2 VARCHAR2(30),
    D_IMAGE3 VARCHAR2(30),
    D_IMAGE4 VARCHAR2(30),
    D_IMAGE5 VARCHAR2(30)
);