-- 프리미엄 동물 분양
DROP SEQUENCE PREBOARD_SEQ;

CREATE SEQUENCE PREBOARD_SEQ
    MAXVALUE 999999
    NOCACHE
    NOCYCLE;


DROP TABLE PREMINUM_BOARD;

CREATE TABLE PREMINUM_BOARD(
    PNUM NUMBER(6) PRIMARY KEY,
    AID REFERENCES ADMIN(AID) NOT NULL,
    PID REFERENCES PREMINUM_ANIMAL(PID) NOT NULL,
    PTITLE VARCHAR2(30) NOT NULL,
    PCONTENT VARCHAR2(3000) NOT NULL,
    PRDATE DATE DEFAULT SYSDATE NOT NULL,
    PHIT NUMBER(6) DEFAULT 0 NOT NULL,
    PIP VARCHAR2(50) NOT NULL,
    PIMAGE1 VARCHAR2(30) NOT NULL, -- 최소 한장 첨부
    PIMAGE2 VARCHAR2(30), 
    PIMAGE3 VARCHAR2(30), 
    PIMAGE4 VARCHAR2(30), 
    PIMAGE5 VARCHAR2(30) 
);