-- 프리미엄 예약 테이블

DROP TABLE PREMINUM_RESERVATION;

CREATE TABLE PREMINUM_RESERVATION(
    MID REFERENCES MEMBER(MID) NOT NULL,
    PID REFERENCES PREMINUM_ANIMAL(PID) NOT NULL,
    PR_DATE DATE NOT NULL
);