DROP TABLE MEMBER;

CREATE TABLE MEMBER(
    ID VARCHAR2(30) PRIMARY KEY,
    PW VARCHAR2(30) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    BIRTH DATE,
    RDATE DATE DEFAULT SYSDATE NOT NULL
);

-- 1. 회원 리스트
SELECT * FROM MEMBER;

-- 2. 회원가입
INSERT INTO MEMBER( ID, PW, NAME, BIRTH )
    VALUES ('aaa','1','홍길동', TO_DATE('1998-12-12','yyyy-MM-dd'));
INSERT INTO MEMBER (ID, PW, NAME, BIRTH)
    VALUES ('bbb','1','김길동', '1995-10-10');

COMMIT;
