DROP TABLE STUDENT;
DROP TABLE MAJOR;

CREATE TABLE MAJOR(
    mNO NUMBER(2) PRIMARY KEY,
    mNAME VARCHAR2(50) NOT NULL );

CREATE TABLE STUDENT(
    sNO NUMBER(7) PRIMARY KEY,
    sNAME VARCHAR2(50) NOT NULL,
    mNO REFERENCES MAJOR(mNO),
    SCORE NUMBER(3) DEFAULT 0 CHECK( SCORE BETWEEN 0 AND 100 ),
    sEXPEL NUMBER(1) DEFAULT 0 CHECK(sEXPEL IN (0,1) ) );

DROP SEQUENCE STD_SEQ;
CREATE SEQUENCE STD_SEQ
    MAXVALUE 999
    NOCACHE
    NOCYCLE;
    
INSERT INTO MAJOR VALUES (1,'빅데이터학');
INSERT INTO MAJOR VALUES (2,'경영정보학');
INSERT INTO MAJOR VALUES (3,'컴퓨터공학');
INSERT INTO MAJOR VALUES (4,'기계공학');
INSERT INTO MAJOR VALUES (5,'인공지능학');

INSERT INTO STUDENT VALUES (TO_CHAR(SYSDATE,'YYYY') || TRIM(TO_CHAR(STD_SEQ.NEXTVAL,'000')),'정우성',1,90,0);
INSERT INTO STUDENT VALUES (TO_CHAR(SYSDATE,'YYYY') || TRIM(TO_CHAR(STD_SEQ.NEXTVAL,'000')),'박세영',1,80,0);
INSERT INTO STUDENT VALUES (TO_CHAR(SYSDATE,'YYYY') || TRIM(TO_CHAR(STD_SEQ.NEXTVAL,'000')),'배수지',3,20,0);
INSERT INTO STUDENT VALUES (TO_CHAR(SYSDATE,'YYYY') || TRIM(TO_CHAR(STD_SEQ.NEXTVAL,'000')),'김제적',3,10,0);
INSERT INTO STUDENT VALUES (TO_CHAR(SYSDATE,'YYYY') || TRIM(TO_CHAR(STD_SEQ.NEXTVAL,'000')),'신길동',2,40,0);

-- 학번검색
SELECT sNO, sNAME, mNAME, SCORE 
   FROM STUDENT S, MAJOR M
        WHERE S.mNO = M.mNO
            AND sNO = 2022001; 

-- 이름 검색
SELECT sNO, sNAME, mNAME, SCORE
    FROM STUDENT S , MAJOR M 
        WHERE S.mNO = M.mNO
            AND sNAME ='배수지';
            
--  전공 검색
SELECT ROWNUM RANK, A.*
    FROM (SELECT sNAME|| '(' || sNO|| ')'  sNAME, mNAME, SCORE
    FROM STUDENT S , MAJOR M
        WHERE S.mNO = M.mNO AND mNAME = '빅데이터학'
            ORDER BY SCORE DESC) A;
            
-- 학생입력
INSERT INTO STUDENT (sNO,sNAME,mNO,SCORE) VALUES
    (TO_CHAR(SYSDATE,'YYYY') || TRIM(TO_CHAR(STD_SEQ.NEXTVAL,'000')),'최진영',(SELECT mNO FROM MAJOR WHERE mNAME='컴퓨터공학'),100);

-- 학생수정
UPDATE STUDENT SET sNAME ='배수지' , mNO=(SELECT mNO FROM MAJOR WHERE mNAME='인공지능학'), SCORE = 50
        WHERE sNO='2022003';
SELECT * FROM STUDENT;

-- 학생출력 ( 제적자 제외)
SELECT ROWNUM || '등'  RANK, sNAME, mNAME|| '(' || mNO || ')'  mNAME, SCORE
    FROM (SELECT sNAME|| '(' || sNO|| ')'  sNAME, mNAME, SCORE,S.mNO
    FROM STUDENT S , MAJOR M
        WHERE S.mNO = M.mNO
            AND sEXPEL != 1
            ORDER BY SCORE DESC) A;

-- 제적처리 업데이트 
UPDATE STUDENT SET sEXPEL = 1
    WHERE sNO = 2022001;

-- 제적자 출력
SELECT ROWNUM || '등'  RANK, sNAME, mNAME|| '(' || mNO || ')'  mNAME, SCORE
    FROM (SELECT sNAME|| '(' || sNO|| ')'  sNAME, mNAME, SCORE,S.mNO
    FROM STUDENT S , MAJOR M
        WHERE S.mNO = M.mNO
            AND sEXPEL != 0
            ORDER BY SCORE DESC) A;


            

            