-- SEQUENCE & TABLE DROP/CREATE
DROP TABLE BOOK CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP SEQUENCE BOOK_SQ;

CREATE TABLE MEMBER(
    MID VARCHAR2(100) PRIMARY KEY,
    MPW VARCHAR2(100) NOT NULL,
    MNAME VARCHAR2(100) NOT NULL,
    MMAIL VARCHAR2(100) NOT NULL,
    MPOST VARCHAR2(100), -- 우편 번호
    MADDR VARCHAR2(100)   -- 주소
);
CREATE SEQUENCE BOOK_SQ
    MAXVALUE 99999999
    NOCYCLE
    NOCACHE;
    
CREATE TABLE BOOK (
    bNUM NUMBER(8) PRIMARY KEY,
    bTITLE VARCHAR2(100) NOT NULL,
    bWRITER VARCHAR2(100) NOT NULL,
    bRDATE DATE DEFAULT SYSDATE NOT NULL,
    bIMG1 VARCHAR2(1000) DEFAULT 'noImg.png' NOT NULL,
    bIMG2 VARCHAR2(1000) DEFAULT 'noImg.png' NOT NULL,
    bINFO VARCHAR2(4000)  
);
-- DUMMY DATA INSERT
INSERT INTO MEMBER VALUES ('aaa', '1', '홍길동', 'hong@naver.com', '12345', '서울' );

INSERT INTO BOOK VALUES( BOOK_SQ.NEXTVAL, 'SPRING', '김작가', SYSDATE, 'noImg.png', 'noImg.png' , '스프링 개념서' );

INSERT INTO BOOK (BNUM, BTITLE, BWRITER, BRDATE, BIMG1, BINFO )
    VALUES( BOOK_SQ.NEXTVAL, 'JSP', '박제이', SYSDATE, 'noImg.png', 'JSP 개념서' );

INSERT INTO BOOK (BNUM, BTITLE, BWRITER, BRDATE,  BINFO )
    VALUES( BOOK_SQ.NEXTVAL, 'JAVA', '이자바', SYSDATE,  'JAVA 개념서' );

commit;
    


 