DROP TABLE CUSTOMER;

CREATE TABLE CUSTOMER(
    ID NUMBER(2) PRIMARY KEY,
    PHONE VARCHAR2(20) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    POINT NUMBER(8,0) DEFAULT 1000 );

DROP SEQUENCE CUS_SEQ;

CREATE SEQUENCE CUS_SEQ
    MAXVALUE 99
    NOCACHE
    NOCYCLE;

-- 더미데이터 입력
INSERT INTO CUSTOMER (ID,PHONE,NAME) VALUES (CUS_SEQ.NEXTVAL,'010-4434-9878','최진영');
INSERT INTO CUSTOMER (ID,PHONE,NAME) VALUES (CUS_SEQ.NEXTVAL,'010-1234-5678','오동준');
INSERT INTO CUSTOMER (ID,PHONE,NAME) VALUES (CUS_SEQ.NEXTVAL,'010-1478-5236','박지원');
INSERT INTO CUSTOMER (ID,PHONE,NAME) VALUES (CUS_SEQ.NEXTVAL,'010-3698-5214','이다솜');
INSERT INTO CUSTOMER (ID,PHONE,NAME) VALUES (CUS_SEQ.NEXTVAL,'010-7894-1593','김유진');

SELECT * FROM CUSTOMER;

-- 가입
INSERT INTO CUSTOMER (ID,PHONE,NAME) VALUES (CUS_SEQ.NEXTVAL,'010-1111-1111','박동규');

-- 폰조회
SELECT PHONE,NAME,POINT FROM CUSTOMER
    WHERE PHONE LIKE '%'||'9878';

-- 전체출력
SELECT PHONE, NAME, POINT FROM CUSTOMER;

COMMIT;













